# Defining GUI executable
if (WIN32)
    add_executable(${PROJECT_NAME}_executable_gui executable/executable-win32.cpp)
else()
    find_package(X11 REQUIRED)
    if(X11_FOUND)
        add_executable(${PROJECT_NAME}_executable_gui executable/executable-x11.cpp)
        target_link_libraries(${PROJECT_NAME}_executable_gui PRIVATE X11)
    elseif(${CMAKE_WARNING_FATAL})
        message(FATAL_ERROR "X11 not found, terminating")
    else()
        message(WARNING "X11 not found, omitting GUI compilation")
    endif()
endif()
target_link_libraries(${PROJECT_NAME}_executable_gui ${${PROJECT_NAME}_PRIVATE_TYPE} ${PROJECT_NAME})