# Defining GUI executable
add_executable(${PROJECT_NAME}_executable_gui)
if (WIN32)
    target_sources(${PROJECT_NAME}_executable_gui PRIVATE "executable/executable-win32.cpp")
else()
    find_package(X11 REQUIRED)
    target_sources(${PROJECT_NAME}_executable_gui PRIVATE "executable/executable-x11.cpp")
    target_link_libraries(${PROJECT_NAME}_executable_gui PRIVATE X11)
endif()
target_link_libraries(${PROJECT_NAME}_executable_gui PUBLIC ${PROJECT_NAME})