###############################
# Install library and headers #
###############################

# Install headers
get_target_property(DEV_INTERFACE_SOURCES ${DEV_CMAKE_NAME} INTERFACE_SOURCES)
install(FILES "${DEV_INTERFACE_SOURCES}"
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${DEV_FILE_NAME}")

# Install library
install(TARGETS ${DEV_CMAKE_NAME}
    EXPORT ${DEV_CMAKE_NAME}_export
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${DEV_FILE_NAME}")