set(CMAKE_SOURCE_DIR "${CMAKE_ARGV3}")
set(CMAKE_BINARY_DIR "${CMAKE_ARGV4}")
set(SOURCE "${CMAKE_SOURCE_DIR}/config/template/Doxyfile")
set(SOURCE_ENV "${CMAKE_BINARY_DIR}/doxyfile-environment.cmake")
set(DEST "${CMAKE_BINARY_DIR}/Doxyfile")
include("${SOURCE_ENV}")
configure_file("${SOURCE}" "${DEST}")